// Helper functions for projection calculations

/**
 * Calculate the final result of a projection
 */
export function calculateProjectionResult(proj) {
    const r = proj.rate / 100;
    const year = parseFloat(proj.days / 365) || 0;

    if (proj.freq === 'ANUAL') {
        return proj.initial + (proj.monthly * 12 * year) + (proj.initial * r * year);
    } else {
        let n = 1;
        if (proj.freq === 'SEMESTRAL') n = 2;
        if (proj.freq === 'TRIMESTRAL') n = 4;
        if (proj.freq === 'MENSUAL') n = 12;
        if (proj.freq === 'DIARIO') n = 365;

        const ratePerPeriod = r / n;
        const periods = n * year;
        const contribPerPeriod = (proj.monthly * 12) / n;

        const fvInitial = proj.initial * Math.pow(1 + ratePerPeriod, periods);
        let fvContribs = 0;
        if (Math.abs(ratePerPeriod) > 0.00000001) {
            fvContribs = contribPerPeriod * (Math.pow(1 + ratePerPeriod, periods) - 1) / ratePerPeriod;
        } else {
            fvContribs = contribPerPeriod * periods;
        }

        return fvInitial + fvContribs;
    }
}

/**
 * Calculate the interest generated by a projection
 */
export function calculateProjectionInterest(proj) {
    const year = parseFloat(proj.days / 365) || 0;
    const totalInvested = proj.initial + (proj.monthly * 12 * year);
    const finalValue = calculateProjectionResult(proj);
    return finalValue - totalInvested;
}
